### ISSUE TITLE
pip install cogsworth[all]  - zsh: no matches found: cogsworth[all]

### ISSUE THREAD

**Issue by JosephKarpinski** [TomWagg/cogsworth#136]
**Which documentation page is causing an issue?**
Please include the URL of the page

# Gaia colour-magnitude diagram
A colour-magnitude diagram using simulated photometry for Gaia.

https://cogsworth.readthedocs.io/en/latest/auto_examples/plot_cmd.html#sphx-glr-auto-examples-plot-cmd-py

**What is the problem?**
Please quote the section and explain either what is misleading/unclear or point out the mistake

ImportError: `isochrones` required for observables predictions with cogsworth
Either install this package directly, or install all optional `cogsworth` dependencies with `pip install cogsworth[all]`

**Suggested solution (optional)**
Suggest how this problem would be solved

Either install this package directly, or install all optional `cogsworth` dependencies with `pip install cogsworth[all]`

**Comment by TomWagg** [comment]
I'm going to close this since it appears to be the same issue as #135 so we can track it there.
