### ISSUE TITLE
Shell escapes for 'cogsworth[extras]'

### ISSUE THREAD

**Issue by gitosaurus** [TomWagg/cogsworth#144]
**Which documentation page is causing an issue?**
https://cogsworth.readthedocs.io/en/latest/pages/install.html

**What is the problem?**
On the "Stable (without conda)" tab, the `pip install cogsworth[extras]` line produces the error

```
zsh: no matches found: cogsworth[extras]
```

**Suggested solution (optional)**
It's only a shell issue, which goes away if you escape the `[]` characters; e.g. `pip install 'cogsworth[extras]'`.

**Comment by TomWagg** [comment]
Nice catch, thanks!
