### ISSUE TITLE
Single star walk/runaways

### ISSUE THREAD

**Issue by TomWagg** [TomWagg/cogsworth#29]
I need to remember to ask @mathren about this. Currently I have it set up so that I only check for walk/runaways if the binary is disrupted. So for single stars I don't find any. But I figure this should still be possible with just a single supernova.

Just not sure if walk/runaways are fast moving stars, or fast moving stars that came out of binaries 🤷🏻

**Comment by TomWagg** [comment]
Tag any star that is fast!

**Comment by TomWagg** [comment]
Thinking more about this @mathren - if I do this then **every** star/binary will be marked as `walkaway-o` since I take any star < 30km/s as a walkaway. Is there a small lower bound I should put on this? (e.g. 15-30km/s is walkaway)

I don't think it makes sense to condition on whether the binary experienced a supernova since the observer wouldn't know that.

**Comment by mathren** [comment]
yeah, that is true. Some people (e.g, [Eldridge+11](https://ui.adsabs.harvard.edu/abs/2011MNRAS.414.3501E/abstract)) use 5km/s (but in the rest frame of the binary center of mass) as an effective definition. I don't think it makes much sense.
I think observers could tell if there was a kick if the star moves weird compared to the surroundings though. So maybe the condition should be |v_star -v_galactic_flow| > 5km/s where the difference is taken between the vectors. Does this make sense?
